Lets HACK Right now ElementalX gov compilation has issue with cputfreq Since folowing declaration is mising
drivers/cpufreq/cpufreq_governor.c: In function 'dbs_check_cpu':
drivers/cpufreq/cpufreq_governor.c:156:27: error: 'deferred_periods' undeclared (first use in this function)
  cdbs->deferred_periods = deferred_periods;
                           ^~~~~~~~~~~~~~~~
drivers/cpufreq/cpufreq_governor.c:156:27: note: each undeclared identifier is reported only once for each function it appears in
  CC      lib/memcopy.o

Since i was not able to find commit that fixes this i took function from source of Elemntal x commits
https://github.com/Shoaib0597/Velocity_MSM8916